services:
  db:
    image: postgres:14.20
    container_name: postgres_container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_data/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - msr

  airflow:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/dags/api-request


    depends_on:
      - db
    networks:
      - msr
    command: >
      bash -c "airflow db migrate && airflow standalone"

volumes:
  pgdata:

networks:
  msr:
    driver: bridge
